#!/bin/bash

COMMAND1="flask --app app run --port 18080"

# Define the child directories
DIR1="./app_server/"

PIPE1="APP_PIPE"

mkfifo "$PIPE1"

# Open the first terminal and run the command in the first child directory
gnome-terminal -- bash -c "cd '$DIR1' && $COMMAND1 > '$PIPE1'; exec bash"

