pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/${machine_name}.crt
  key: /etc/nebula/${machine_name}.key

static_host_map:
  "192.168.100.1": ["${lighthouse_ip}:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100


  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: 2377
      proto: any
      host: any
    
    - port: 7946
      proto: any
      host: any
    
    - port: 4789
      proto: any
      host: any
